### ISSUE TITLE
NPM Build Command Error

### ISSUE THREAD

**Issue by sergchernata** [Remmeauth/remme-block-explorer#2]
According to [the installation guide](https://github.com/Remmeauth/remme-block-explorer#installation), we're supposed to run `npm build`.

However, the following error is returned:

> npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?

Running Node v8.9.1

**Comment by ArtemFrantsiian** [comment]
Yes, we meant `npm run build`.
Readme has already been fixed.

**Comment by sergchernata** [comment]
Please update [in the docs](https://docs.remme.io/remme-block-explorer/docs/#installation) as well.
