### ISSUE TITLE
Docker Compose Up Error

### ISSUE THREAD

**Issue by sergchernata** [Remmeauth/remme-block-explorer#3]
According to [the installation guide](https://github.com/Remmeauth/remme-block-explorer#installation), we're supposed to run `docker-compose up`.

However, the following error is returned:

> Starting nginx_block_explorer ... done
Starting remme_block_explorer ... error
>
> ERROR: for remme_block_explorer  Cannot start service remme_block_explorer: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 21\"": unknown
>
> ERROR: for remme_block_explorer  Cannot start service remme_block_explorer: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 21\"": unknown
ERROR: Encountered errors while bringing up the project.

Running:
Engine: 18.06.1-ce
Compose: 1.22.0

**Comment by eugene-babichenko** [comment]
Thanks for reporting! We will fix it as soon as possible.
